### PR TITLE
Increase maximum number of hits for /v2/filter to 500

### LINKED ISSUE #132: Filter Search never returns more than ten results
When a node contains spaces in its title, filtering for tags does not work.

This pull request introduces tests to prove it and investigate the issue: https://github.com/rundsk/dsk/pull/131

### PR DESCRIPTION
**Pull request by ChristophLabacher**
This pull request increases the maximum number of results returned form a FilterSearch request to 100. Right now the limit is 10.

FilterSearch results are meant to be exhaustive, as described in https://rundsk.com/tree/Development/Architecture/API?t=readme§filtering-and-searching: “filter […] always returns all matched results […]”.

PTAL @mariuswilms 
Fixes #132

### CODE REVIEW

**Comment by ChristophLabacher** [comment]
@mariuswilms should we also raise the limit for the full search? I think having a cap makes much more sense here, but 10 seems a bit low?

**Comment by mariuswilms** [comment]
> @mariuswilms should we also raise the limit for the full search? I think having a cap makes much more sense here, but 10 seems a bit low?

I agree, How about 50? I can do that as it is outside the scope of this (neatly scoped) PR.

**Comment by ChristophLabacher** [comment]
@mariuswilms 50 sound good – please do!

I introduced the constant.

File: internal/search/main.go [hunk 1]
```diff
@@ -15,16 +15,18 @@ import (
...
 	"github.com/blevesearch/bleve/analysis/analyzer/keyword"
 	"github.com/blevesearch/bleve/analysis/analyzer/simple"
 	"github.com/blevesearch/bleve/analysis/lang/de"
 	"github.com/blevesearch/bleve/analysis/lang/en"
 	"github.com/blevesearch/bleve/mapping"
 	"github.com/blevesearch/bleve/search/query"
+	"github.com/rundsk/dsk/internal/ddt"
 )
 
+const FILTER_RESULT_LIMIT = 500
```
Comment (mariuswilms) [inline internal/search/main.go:28]: Go does constant names a little different, see https://stackoverflow.com/questions/22688906/go-naming-conventions-for-const they follow the same rules as variables. Can you apply that small change?

```suggestion
const FilterResultLimit = 500
```

File: internal/search/main.go [hunk 2]
```diff
@@ -382,6 +384,7 @@ func (s *Search) FilterSearch(q string) ([]*ddt.Node, int, time.Duration, bool,
 
 	cq := bleve.NewConjunctionQuery(pqs...)
 	req := bleve.NewSearchRequest(cq)
+	req.Size = FILTER_RESULT_LIMIT
```
Comment (mariuswilms) [inline internal/search/main.go:387]:
```suggestion
	req.Size = FilterResultLimit
```

File: internal/search/main.go (hunk 1 above)
Comment (ChristophLabacher) [reply internal/search/main.go:28]: ha, I was mislead by https://www.golangprograms.com/go-language/constants.html
